info:
  component: zuul server app
  
server: 
  port: 2020
  
spring:
  config:
    name: zuulserver
  application:
    name: zuulserver
    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    student-service:
      path: /student-api/**
      service-id: STUDENT-SERVICE
    feign-client:
      path: /feign-empleado/**  
      service-id: FEIGN-CLIENT   
  ribbonIsolationStrategy: THREAD 
       

